"""MLASIC — ML model to ASIC compiler."""

from mlasic.dag_scheduler import (
    ActivationLifetime,
    ActivationLifetimeAnalyzer,
    DAGSchedule,
    DAGScheduler,
    SRAMBudgetPlanner,
)
from mlasic.exceptions import (
    IRValidationError,
    ParseError,
    ShapeInferenceError,
    UnsupportedOperatorError,
)
from mlasic.golden_vectors import (
    GoldenVector,
    GoldenVectorGenerator,
    GoldenVectorSet,
    TestVector,
    TestVectorSet,
)
from mlasic.int8_interpreter import INT8Interpreter
from mlasic.interpreter import IRInterpreter
from mlasic.ir import (
    ConvAttrs,
    DAGLayerSchedule,
    FusedActivationAttrs,
    FusedConvAttrs,
    FusedLayerNormAttrs,
    FusedLinearAttrs,
    GemmAttrs,
    Graph,
    HardwareConstraints,
    IRValidator,
    LayerSchedule,
    NormAttrs,
    OpNode,
    OpType,
    PoolAttrs,
    QuantParams,
    Schedule,
    Tensor,
    TensorType,
)
from mlasic.optimization import (
    ActivationFusionPass,
    BatchNormFoldingPass,
    ConstantFoldingPass,
    ConvBatchNormFoldingPass,
    ConvFusionPass,
    ConvQuantizationPass,
    DeadCodeEliminationPass,
    LayerNormFusionPass,
    OperatorFusionPass,
    OptimizationPass,
    PassManager,
    QuantizationPass,
)
from mlasic.rom_mapper import (
    DieAreaEstimate,
    DieAreaEstimator,
    WeightCompressor,
    WeightROMMapper,
)
from mlasic.rtl_gen import RTLGenerator
from mlasic.scheduler import CycleBreakdown, Scheduler, schedule_to_json
from mlasic.testbench_gen import (
    FunctionalCoverage,
    TestbenchConfig,
    TestbenchGenerator,
    VerifConfig,
    VerifGenerator,
)
from mlasic.tile_mapper import (
    FabricConfig,
    TileConfig,
    TileConstraints,
    TileMapper,
    TileType,
    WeightPartitioner,
)
from mlasic.weight_packer import WeightPacker, load_bias_mem, load_weight_mem

__all__ = [
    "ActivationFusionPass",
    "FunctionalCoverage",
    "GoldenVector",
    "GoldenVectorGenerator",
    "GoldenVectorSet",
    "ActivationLifetime",
    "ActivationLifetimeAnalyzer",
    "BatchNormFoldingPass",
    "ConstantFoldingPass",
    "ConvAttrs",
    "ConvBatchNormFoldingPass",
    "ConvFusionPass",
    "ConvQuantizationPass",
    "CycleBreakdown",
    "DAGLayerSchedule",
    "DAGSchedule",
    "DAGScheduler",
    "DeadCodeEliminationPass",
    "DieAreaEstimate",
    "DieAreaEstimator",
    "FabricConfig",
    "FusedActivationAttrs",
    "FusedConvAttrs",
    "FusedLayerNormAttrs",
    "FusedLinearAttrs",
    "GemmAttrs",
    "Graph",
    "HardwareConstraints",
    "INT8Interpreter",
    "IRInterpreter",
    "IRValidationError",
    "IRValidator",
    "LayerNormFusionPass",
    "LayerSchedule",
    "NormAttrs",
    "OpNode",
    "OpType",
    "OperatorFusionPass",
    "OptimizationPass",
    "ParseError",
    "PassManager",
    "PoolAttrs",
    "QuantParams",
    "QuantizationPass",
    "RTLGenerator",
    "SRAMBudgetPlanner",
    "Schedule",
    "Scheduler",
    "ShapeInferenceError",
    "Tensor",
    "TensorType",
    "TestVector",
    "TestVectorSet",
    "TestbenchConfig",
    "TestbenchGenerator",
    "VerifConfig",
    "VerifGenerator",
    "TileConfig",
    "TileConstraints",
    "TileMapper",
    "TileType",
    "UnsupportedOperatorError",
    "WeightCompressor",
    "WeightPacker",
    "WeightPartitioner",
    "WeightROMMapper",
    "load_bias_mem",
    "load_weight_mem",
    "schedule_to_json",
]
