"""Graph → RTL IR lowering.

This module is the *back-end front-end*: it consumes a scheduled
``mlasic.ir.Graph`` and produces an ``mlasic.rtl_ir.RTLModule`` that
``mlasic.rtl_emit`` can serialize to SystemVerilog.

There are two entry points:

  * ``lower_mlp_top``        — for pure FusedLinear/FusedLinearReLU chains.
                              Replaces ``RTLGenerator.generate_accelerator_top``.
  * ``lower_tile_fabric_top`` — for tile-fabric (CNN/Transformer/DAG) models.
                              Replaces ``generate_tile_accelerator_top`` +
                              ``generate_tile_fabric_sv``.

Both entry points produce the same artifact shape: an ``RTLModule`` named
``accelerator_top`` (or a ``ModuleLibrary`` of cooperating modules).

Structural body items (instances, assigns) are first-class IR. Behavioral
SystemVerilog (FSM next-state ``always_comb``, FF blocks, counters) is
captured as ``RTLRawBlock`` — opaque to RTL passes but tracked for liveness
through the ``defines``/``uses`` annotations. This is the same trade-off
LLVM makes with ``inline asm``: keep the IR finite, accept opaque leaves.
"""

from __future__ import annotations

import math
from typing import TYPE_CHECKING

from mlasic.ir import (
    FusedLinearAttrs,
    Graph,
    HardwareConstraints,
)
from mlasic.rtl_ir import (
    ModuleLibrary,
    RTLDir,
    RTLModule,
    RTLType,
)

if TYPE_CHECKING:
    from mlasic.tile_mapper import FabricConfig


# ---------------------------------------------------------------------------
# parameters.svh — emitted as a leaf header, not an RTLModule
# ---------------------------------------------------------------------------


def render_mlp_parameters_svh(
    graph: Graph, constraints: HardwareConstraints
) -> str:
    """Render the ``parameters.svh`` constants header for the MLP path."""
    ordered_names = graph.topological_order()
    ordered_nodes = [graph.nodes[n] for n in ordered_names]
    num_layers = len(ordered_nodes)

    in_dims: list[int] = []
    out_dims: list[int] = []
    relus: list[bool] = []
    weight_bases: list[int] = []
    bias_bases: list[int] = []
    requant_ms: list[int] = []
    requant_shifts: list[int] = []
    requant_zps: list[int] = []
    num_tiles_arr: list[int] = []

    max_dim = 0
    for node in ordered_nodes:
        ls = node.schedule_info
        attrs = node.fused_attrs
        assert ls is not None, f"Node {node.name} missing schedule_info"
        assert isinstance(attrs, FusedLinearAttrs), (
            f"Node {node.name} missing FusedLinearAttrs"
        )

        in_dims.append(ls.input_dim)
        out_dims.append(ls.output_dim)
        relus.append(ls.has_relu)
        weight_bases.append(ls.weight_start_row)
        bias_bases.append(ls.bias_start_row)
        num_tiles_arr.append(ls.num_tiles)
        requant_ms.append(attrs.requant_scale_fixed or 0)
        requant_shifts.append(attrs.requant_shift or 0)
        if attrs.output_quant is not None:
            requant_zps.append(attrs.output_quant.zero_point)
        else:
            requant_zps.append(0)
        max_dim = max(max_dim, ls.input_dim, ls.output_dim)

    weight_depth = constraints.weight_bank_depth
    bias_depth = constraints.bias_bank_depth
    act_depth = max_dim // 8
    total_weight_rows = sum(n.schedule_info.weight_rows for n in ordered_nodes)
    total_bias_rows = sum(n.schedule_info.bias_rows for n in ordered_nodes)
    last = num_layers - 1

    def _arr(items: list[str]) -> str:
        return "'{" + ", ".join(items) + "}"

    def _zp_lit(z: int) -> str:
        return f"-8'sd{abs(z)}" if z < 0 else f"8'sd{z}"

    lines = [
        "// parameters.svh — Auto-generated by MLASIC RTL Generator",
        f"// Model: {graph.name}",
        f"// Layers: {num_layers}",
        "",
        "/* verilator lint_off UNUSEDPARAM */",
        "",
        f"localparam int NUM_LAYERS   = {num_layers};",
        f"localparam int MAX_DIM      = {max_dim};",
        f"localparam int PARALLELISM  = {constraints.max_parallelism};",
        "localparam int AXI_DATA_W   = 64;",
        f"localparam int WEIGHT_DEPTH = {weight_depth};",
        f"localparam int BIAS_DEPTH   = {bias_depth};",
        f"localparam int ACT_DEPTH    = {act_depth};",
        f"localparam int TOTAL_WEIGHT_ROWS = {total_weight_rows};",
        f"localparam int TOTAL_BIAS_ROWS   = {total_bias_rows};",
        "",
        "// Per-layer dimensions",
        f"localparam logic [15:0] LAYER_IN_DIM  [0:{last}] = "
        + _arr([f"16'd{d}" for d in in_dims])
        + ";",
        f"localparam logic [15:0] LAYER_OUT_DIM [0:{last}] = "
        + _arr([f"16'd{d}" for d in out_dims])
        + ";",
        f"localparam logic [15:0] LAYER_NUM_TILES [0:{last}] = "
        + _arr([f"16'd{t}" for t in num_tiles_arr])
        + ";",
        f"localparam logic [0:0]  LAYER_RELU   [0:{last}] = "
        + _arr([f"1'b{int(r)}" for r in relus])
        + ";",
        "",
        "// Weight/bias SRAM base addresses",
        f"localparam logic [15:0] WEIGHT_BASE [0:{last}] = "
        + _arr([f"16'd{b}" for b in weight_bases])
        + ";",
        f"localparam logic [15:0] BIAS_BASE   [0:{last}] = "
        + _arr([f"16'd{b}" for b in bias_bases])
        + ";",
        "",
        "// Requantization parameters",
        f"localparam logic [31:0] REQUANT_M     [0:{last}] = "
        + _arr([f"32'd{m}" for m in requant_ms])
        + ";",
        f"localparam logic [5:0]  REQUANT_SHIFT [0:{last}] = "
        + _arr([f"6'd{s}" for s in requant_shifts])
        + ";",
        f"localparam logic signed [7:0]  REQUANT_ZP    [0:{last}] = "
        + _arr([_zp_lit(z) for z in requant_zps])
        + ";",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# MLP accelerator_top lowering
# ---------------------------------------------------------------------------


def lower_mlp_top(graph: Graph, constraints: HardwareConstraints) -> RTLModule:
    """Lower an MLP graph to a structural ``accelerator_top`` ``RTLModule``.

    Produces the same Verilog (modulo whitespace) as the original
    ``RTLGenerator.generate_accelerator_top()``, but as IR objects rather
    than a giant f-string.
    """
    ordered_names = graph.topological_order()
    num_layers = len(ordered_names)
    parallelism = constraints.max_parallelism
    bias_idx_w = max(1, math.ceil(math.log2(parallelism)))

    mod = RTLModule(
        name="accelerator_top",
        header_comment=(
            f"accelerator_top.sv — Auto-generated by MLASIC RTL Generator\n"
            f"Model: {graph.name}\n"
            f"Layers: {num_layers}"
        ),
    )
    mod.add_include("parameters.svh")

    _add_top_ports(mod)
    _add_top_signals(mod, parallelism=parallelism, bias_idx_w=bias_idx_w)
    _add_top_lint_pragma(mod)
    _add_sram_instances(mod, parallelism=parallelism)
    _add_activation_mux(mod)
    _add_axi_lite_ctrl(mod)
    _add_axi_stream_io(mod)
    _add_mac_array(mod)
    _add_layer_controller(mod)
    _add_top_fsm(mod)

    mod.verify()
    return mod


# ---------------------------------------------------------------------------
# Top-level port and signal scaffolding
# ---------------------------------------------------------------------------


def _add_top_ports(mod: RTLModule) -> None:
    L = RTLType.logic
    mod.add_port("clk", RTLDir.INPUT, L())
    mod.add_port("rst_n", RTLDir.INPUT, L())

    # AXI-Lite CSR
    mod.add_port("s_axi_awaddr", RTLDir.INPUT, L(width=8))
    mod.add_port("s_axi_awvalid", RTLDir.INPUT, L())
    mod.add_port("s_axi_awready", RTLDir.OUTPUT, L())
    mod.add_port("s_axi_wdata", RTLDir.INPUT, L(width=32))
    mod.add_port("s_axi_wstrb", RTLDir.INPUT, L(width=4))
    mod.add_port("s_axi_wvalid", RTLDir.INPUT, L())
    mod.add_port("s_axi_wready", RTLDir.OUTPUT, L())
    mod.add_port("s_axi_bresp", RTLDir.OUTPUT, L(width=2))
    mod.add_port("s_axi_bvalid", RTLDir.OUTPUT, L())
    mod.add_port("s_axi_bready", RTLDir.INPUT, L())
    mod.add_port("s_axi_araddr", RTLDir.INPUT, L(width=8))
    mod.add_port("s_axi_arvalid", RTLDir.INPUT, L())
    mod.add_port("s_axi_arready", RTLDir.OUTPUT, L())
    mod.add_port("s_axi_rdata", RTLDir.OUTPUT, L(width=32))
    mod.add_port("s_axi_rresp", RTLDir.OUTPUT, L(width=2))
    mod.add_port("s_axi_rvalid", RTLDir.OUTPUT, L())
    mod.add_port("s_axi_rready", RTLDir.INPUT, L())

    # AXI-Stream input
    mod.add_port("s_axis_tdata", RTLDir.INPUT, L(width="AXI_DATA_W"))
    mod.add_port("s_axis_tvalid", RTLDir.INPUT, L())
    mod.add_port("s_axis_tready", RTLDir.OUTPUT, L())
    mod.add_port("s_axis_tlast", RTLDir.INPUT, L())
    mod.add_port("s_axis_tkeep", RTLDir.INPUT, L(width=8))

    # AXI-Stream output
    mod.add_port("m_axis_tdata", RTLDir.OUTPUT, L(width="AXI_DATA_W"))
    mod.add_port("m_axis_tvalid", RTLDir.OUTPUT, L())
    mod.add_port("m_axis_tready", RTLDir.INPUT, L())
    mod.add_port("m_axis_tlast", RTLDir.OUTPUT, L())
    mod.add_port("m_axis_tkeep", RTLDir.OUTPUT, L(width=8))

    mod.add_port("irq", RTLDir.OUTPUT, L())


def _add_top_signals(mod: RTLModule, parallelism: int, bias_idx_w: int) -> None:
    L = RTLType.logic

    # FSM state encoding
    mod.add_raw(
        code=(
            "typedef enum logic [2:0] {\n"
            "    S_IDLE,\n"
            "    S_RECV_IN,\n"
            "    S_RUN_LAYER,\n"
            "    S_NEXT_LAYER,\n"
            "    S_SEND_OUT,\n"
            "    S_DONE\n"
            "} accel_state_t;\n"
            "\n"
            "accel_state_t state, state_next;\n"
            "logic [15:0] layer_idx;"
        ),
        defines=("state", "state_next", "layer_idx", "accel_state_t"),
        label="Top-level FSM state",
    )

    # CSR control/status
    mod.add_signal("ctrl_start", L())
    mod.add_signal("ctrl_soft_rst", L())
    mod.add_signal("ctrl_continuous", L())
    mod.add_signal("irq_en_out", L())
    mod.add_signal("status_idle", L())
    mod.add_signal("status_busy", L())
    mod.add_signal("status_done_reg", L())
    mod.add_signal("status_error", L())
    mod.add_signal("cycle_count_reg", L(width=32))
    mod.add_signal("inf_count_reg", L(width=32))
    mod.add_signal("error_code_reg", L(width=32))
    mod.add_signal("irq_done_pulse", L())
    mod.add_signal("irq_error_pulse", L())

    # Weight SRAM
    mod.add_signal("weight_addr", L(width=16))
    mod.add_signal("weight_rdata", L(width=f"{parallelism}*8"))

    # Bias SRAM
    mod.add_signal("bias_addr", L(width=16))
    mod.add_signal("bias_rdata", L(width=f"{parallelism}*32"))

    # Activation ping-pong
    mod.add_signal("input_bank_sel", L())
    mod.add_signal("act_rd_addr", L(width="$clog2(ACT_DEPTH)"))
    mod.add_signal("act_wr_addr", L(width="$clog2(ACT_DEPTH)"))
    mod.add_signal("act_rd_data", L(width="AXI_DATA_W"))
    mod.add_signal("act_wr_data", L(width="AXI_DATA_W"))
    mod.add_signal("act_wr_en", L())

    # Direct access for AXI-Stream
    mod.add_signal("axis_in_addr", L(width="$clog2(ACT_DEPTH)"))
    mod.add_signal("axis_out_addr", L(width="$clog2(ACT_DEPTH)"))
    mod.add_signal("axis_in_we", L())
    mod.add_signal("axis_in_wdata", L(width="AXI_DATA_W"))
    mod.add_signal("axis_out_rdata", L(width="AXI_DATA_W"))

    # AXI-Stream control
    mod.add_signal("axis_in_enable", L())
    mod.add_signal("axis_in_done", L())
    mod.add_signal("axis_out_enable", L())
    mod.add_signal("axis_out_done", L())

    # MAC array signals
    mod.add_signal("mac_start", L())
    mod.add_signal("mac_input_dim", L(width=16))
    mod.add_signal("mac_has_relu", L())
    mod.add_signal("mac_input_data", L(width=8, signed=True))
    mod.add_signal("mac_input_valid", L())
    mod.add_signal("mac_bias_valid", L())
    mod.add_signal("mac_bias_idx", L(width=bias_idx_w))
    mod.add_signal("mac_bias_data", L(width=32, signed=True))
    mod.add_signal("mac_scale", L(width=32))
    mod.add_signal("mac_shift", L(width=6))
    mod.add_signal("mac_zp", L(width=8, signed=True))
    mod.add_signal(
        "mac_output_data",
        RTLType(width=8, signed=True, unpacked_dims=(f"0:{parallelism}-1",)),
    )
    mod.add_signal("mac_output_valid", L())
    mod.add_signal("mac_done_sig", L())

    # Layer controller
    mod.add_signal("layer_start", L())
    mod.add_signal("layer_done_sig", L())

    # Cycle counter
    mod.add_signal("cycle_counter", L(width=32))
    mod.add_signal("counting", L())


def _add_top_lint_pragma(mod: RTLModule) -> None:
    mod.add_raw(
        code=(
            "/* verilator lint_off UNUSEDSIGNAL */\n"
            "/* verilator lint_off WIDTHTRUNC */\n"
            "/* verilator lint_off WIDTHEXPAND */\n"
            "/* verilator lint_off PINMISSING */"
        ),
        label="Verilator lint suppressions",
    )


# ---------------------------------------------------------------------------
# SRAM banks
# ---------------------------------------------------------------------------


def _add_sram_instances(mod: RTLModule, parallelism: int) -> None:
    p = parallelism

    mod.add_instance(
        name="weight_bank",
        module_type="sram_bank",
        params={
            "DEPTH": "WEIGHT_DEPTH",
            "WIDTH": f"{p}*8",
            "INIT_FILE": '"weight_bank.mem"',
        },
        port_map={
            "clk": "clk",
            "addr": "weight_addr[$clog2(WEIGHT_DEPTH)-1:0]",
            "we": "1'b0",
            "wdata": "{" + f"{p}*8{{1'b0}}" + "}",
            "rdata": "weight_rdata",
        },
        comment="Unified weight bank",
    )

    mod.add_instance(
        name="bias_bank",
        module_type="sram_bank",
        params={
            "DEPTH": "BIAS_DEPTH",
            "WIDTH": f"{p}*32",
            "INIT_FILE": '"bias_bank.mem"',
        },
        port_map={
            "clk": "clk",
            "addr": "bias_addr[$clog2(BIAS_DEPTH)-1:0]",
            "we": "1'b0",
            "wdata": "{" + f"{p}*32{{1'b0}}" + "}",
            "rdata": "bias_rdata",
        },
        comment="Bias bank",
    )

    # Activation ping-pong buffers (A and B)
    L = RTLType.logic
    for sig in ("act_a_addr", "act_b_addr"):
        mod.add_signal(sig, L(width="$clog2(ACT_DEPTH)"))
    for sig in ("act_a_we", "act_b_we"):
        mod.add_signal(sig, L())
    for sig in ("act_a_wdata", "act_b_wdata", "act_a_rdata", "act_b_rdata"):
        mod.add_signal(sig, L(width="AXI_DATA_W"))

    mod.add_instance(
        name="act_a",
        module_type="sram_bank",
        params={"DEPTH": "ACT_DEPTH", "WIDTH": "AXI_DATA_W"},
        port_map={
            "clk": "clk",
            "addr": "act_a_addr",
            "we": "act_a_we",
            "wdata": "act_a_wdata",
            "rdata": "act_a_rdata",
        },
    )
    mod.add_instance(
        name="act_b",
        module_type="sram_bank",
        params={"DEPTH": "ACT_DEPTH", "WIDTH": "AXI_DATA_W"},
        port_map={
            "clk": "clk",
            "addr": "act_b_addr",
            "we": "act_b_we",
            "wdata": "act_b_wdata",
            "rdata": "act_b_rdata",
        },
    )


def _add_activation_mux(mod: RTLModule) -> None:
    mod.add_assign(
        "input_bank_sel", "layer_idx[0]", comment="bank select from layer index"
    )

    mod.add_raw(
        code=(
            "always_comb begin\n"
            "    if (state == S_RECV_IN) begin\n"
            "        // AXI-Stream input writes to bank A\n"
            "        act_a_addr = axis_in_addr;\n"
            "        act_a_we = axis_in_we;\n"
            "        act_a_wdata = axis_in_wdata;\n"
            "        act_b_addr = {$clog2(ACT_DEPTH){1'b0}};\n"
            "        act_b_we = 1'b0;\n"
            "        act_b_wdata = {AXI_DATA_W{1'b0}};\n"
            "    end else if (state == S_SEND_OUT) begin\n"
            "        // AXI-Stream output reads from bank A (last layer)\n"
            "        act_a_addr = axis_out_addr;\n"
            "        act_a_we = 1'b0;\n"
            "        act_a_wdata = {AXI_DATA_W{1'b0}};\n"
            "        act_b_addr = {$clog2(ACT_DEPTH){1'b0}};\n"
            "        act_b_we = 1'b0;\n"
            "        act_b_wdata = {AXI_DATA_W{1'b0}};\n"
            "    end else if (!input_bank_sel) begin\n"
            "        // Read from A, write to B\n"
            "        act_a_addr = act_rd_addr;\n"
            "        act_a_we = 1'b0;\n"
            "        act_a_wdata = {AXI_DATA_W{1'b0}};\n"
            "        act_b_addr = act_wr_addr;\n"
            "        act_b_we = act_wr_en;\n"
            "        act_b_wdata = act_wr_data;\n"
            "    end else begin\n"
            "        // Read from B, write to A\n"
            "        act_b_addr = act_rd_addr;\n"
            "        act_b_we = 1'b0;\n"
            "        act_b_wdata = {AXI_DATA_W{1'b0}};\n"
            "        act_a_addr = act_wr_addr;\n"
            "        act_a_we = act_wr_en;\n"
            "        act_a_wdata = act_wr_data;\n"
            "    end\n"
            "end"
        ),
        defines=(
            "act_a_addr",
            "act_a_we",
            "act_a_wdata",
            "act_b_addr",
            "act_b_we",
            "act_b_wdata",
        ),
        uses=(
            "state",
            "axis_in_addr",
            "axis_in_we",
            "axis_in_wdata",
            "axis_out_addr",
            "input_bank_sel",
            "act_rd_addr",
            "act_wr_addr",
            "act_wr_en",
            "act_wr_data",
        ),
        label="Activation bank mux",
    )

    mod.add_assign(
        "act_rd_data", "input_bank_sel ? act_b_rdata : act_a_rdata"
    )
    mod.add_assign("axis_out_rdata", "act_a_rdata")


# ---------------------------------------------------------------------------
# AXI-Lite control
# ---------------------------------------------------------------------------


def _add_axi_lite_ctrl(mod: RTLModule) -> None:
    mod.add_instance(
        name="u_ctrl",
        module_type="axi_lite_ctrl",
        params={"VERSION": "32'h0001_0000"},
        port_map={
            "clk": "clk",
            "rst_n": "rst_n",
            "s_axi_awaddr": "s_axi_awaddr",
            "s_axi_awvalid": "s_axi_awvalid",
            "s_axi_awready": "s_axi_awready",
            "s_axi_wdata": "s_axi_wdata",
            "s_axi_wstrb": "s_axi_wstrb",
            "s_axi_wvalid": "s_axi_wvalid",
            "s_axi_wready": "s_axi_wready",
            "s_axi_bresp": "s_axi_bresp",
            "s_axi_bvalid": "s_axi_bvalid",
            "s_axi_bready": "s_axi_bready",
            "s_axi_araddr": "s_axi_araddr",
            "s_axi_arvalid": "s_axi_arvalid",
            "s_axi_arready": "s_axi_arready",
            "s_axi_rdata": "s_axi_rdata",
            "s_axi_rresp": "s_axi_rresp",
            "s_axi_rvalid": "s_axi_rvalid",
            "s_axi_rready": "s_axi_rready",
            "ctrl_start": "ctrl_start",
            "ctrl_soft_rst": "ctrl_soft_rst",
            "ctrl_continuous": "ctrl_continuous",
            "irq_en": "irq_en_out",
            "status_idle": "status_idle",
            "status_busy": "status_busy",
            "status_done": "status_done_reg",
            "status_error": "status_error",
            "cycle_count": "cycle_count_reg",
            "inf_count": "inf_count_reg",
            "error_code": "error_code_reg",
            "layer_status": "layer_idx[1:0]",
            "irq_done": "irq_done_pulse",
            "irq_error": "irq_error_pulse",
            "irq": "irq",
        },
        comment="AXI-Lite control / status registers",
    )


# ---------------------------------------------------------------------------
# AXI-Stream input/output
# ---------------------------------------------------------------------------


def _add_axi_stream_io(mod: RTLModule) -> None:
    mod.add_instance(
        name="u_axis_in",
        module_type="axi_stream_in",
        params={
            "AXI_DATA_W": "AXI_DATA_W",
            "NUM_BEATS": "ACT_DEPTH",
            "ACT_DEPTH": "ACT_DEPTH",
        },
        port_map={
            "clk": "clk",
            "rst_n": "rst_n",
            "enable": "axis_in_enable",
            "done": "axis_in_done",
            "s_axis_tdata": "s_axis_tdata",
            "s_axis_tvalid": "s_axis_tvalid",
            "s_axis_tready": "s_axis_tready",
            "s_axis_tlast": "s_axis_tlast",
            "s_axis_tkeep": "s_axis_tkeep",
            "act_addr": "axis_in_addr",
            "act_we": "axis_in_we",
            "act_wdata": "axis_in_wdata",
        },
    )

    mod.add_instance(
        name="u_axis_out",
        module_type="axi_stream_out",
        params={
            "AXI_DATA_W": "AXI_DATA_W",
            "NUM_BEATS": "ACT_DEPTH",
            "ACT_DEPTH": "ACT_DEPTH",
        },
        port_map={
            "clk": "clk",
            "rst_n": "rst_n",
            "enable": "axis_out_enable",
            "done": "axis_out_done",
            "m_axis_tdata": "m_axis_tdata",
            "m_axis_tvalid": "m_axis_tvalid",
            "m_axis_tready": "m_axis_tready",
            "m_axis_tlast": "m_axis_tlast",
            "m_axis_tkeep": "m_axis_tkeep",
            "act_addr": "axis_out_addr",
            "act_rdata": "axis_out_rdata",
        },
    )


# ---------------------------------------------------------------------------
# Compute: shared MAC array
# ---------------------------------------------------------------------------


def _add_mac_array(mod: RTLModule) -> None:
    mod.add_instance(
        name="u_mac",
        module_type="mac_array",
        params={"PARALLELISM": "PARALLELISM", "DATA_W": "8", "ACC_W": "32"},
        port_map={
            "clk": "clk",
            "rst_n": "rst_n",
            "start": "mac_start",
            "input_dim": "mac_input_dim",
            "has_relu": "mac_has_relu",
            "weight_data": "weight_rdata",
            "weight_valid": "1'b1",
            "input_data": "mac_input_data",
            "input_valid": "mac_input_valid",
            "bias_data": "mac_bias_data",
            "bias_valid": "mac_bias_valid",
            "bias_idx": "mac_bias_idx",
            "scale": "mac_scale",
            "shift": "mac_shift",
            "zero_point": "mac_zp",
            "output_data": "mac_output_data",
            "output_valid": "mac_output_valid",
            "done": "mac_done_sig",
        },
        comment="Shared MAC array (time-multiplexed across layers)",
    )


# ---------------------------------------------------------------------------
# Compute: per-layer fused_linear_relu controller
# ---------------------------------------------------------------------------


def _add_layer_controller(mod: RTLModule) -> None:
    mod.add_instance(
        name="u_layer_ctrl",
        module_type="fused_linear_relu",
        params={
            "PARALLELISM": "PARALLELISM",
            "DATA_W": "8",
            "ACC_W": "32",
            "ACT_DEPTH": "ACT_DEPTH",
            "ACT_WIDTH": "AXI_DATA_W",
        },
        port_map={
            "clk": "clk",
            "rst_n": "rst_n",
            "start": "layer_start",
            "input_dim": "LAYER_IN_DIM[layer_idx]",
            "output_dim": "LAYER_OUT_DIM[layer_idx]",
            "num_tiles": "LAYER_NUM_TILES[layer_idx]",
            "has_relu": "LAYER_RELU[layer_idx]",
            "weight_base": "WEIGHT_BASE[layer_idx]",
            "bias_base": "BIAS_BASE[layer_idx]",
            "requant_scale": "REQUANT_M[layer_idx]",
            "requant_shift": "REQUANT_SHIFT[layer_idx]",
            "requant_zp": "REQUANT_ZP[layer_idx]",
            "weight_addr": "weight_addr",
            "weight_rdata": "weight_rdata",
            "bias_addr": "bias_addr",
            "bias_rdata": "bias_rdata",
            "act_rd_addr": "act_rd_addr",
            "act_rd_data": "act_rd_data",
            "act_wr_addr": "act_wr_addr",
            "act_wr_en": "act_wr_en",
            "act_wr_data": "act_wr_data",
            "mac_start": "mac_start",
            "mac_input_dim": "mac_input_dim",
            "mac_has_relu": "mac_has_relu",
            "mac_scale": "mac_scale",
            "mac_shift": "mac_shift",
            "mac_zp": "mac_zp",
            "mac_input_data": "mac_input_data",
            "mac_input_valid": "mac_input_valid",
            "mac_bias_valid": "mac_bias_valid",
            "mac_bias_idx": "mac_bias_idx",
            "mac_bias_data": "mac_bias_data",
            "mac_output_data": "mac_output_data",
            "mac_output_valid": "mac_output_valid",
            "mac_done": "mac_done_sig",
            "layer_done": "layer_done_sig",
        },
        comment="Per-layer streaming controller",
    )


# ---------------------------------------------------------------------------
# Top-level FSM (FSM next-state, regs, counters — opaque raw block)
# ---------------------------------------------------------------------------


def _add_top_fsm(mod: RTLModule) -> None:
    mod.add_raw(
        code=(
            "// FSM next-state\n"
            "always_comb begin\n"
            "    state_next = state;\n"
            "    case (state)\n"
            "        S_IDLE:       if (ctrl_start) state_next = S_RECV_IN;\n"
            "        S_RECV_IN:    if (axis_in_done) state_next = S_RUN_LAYER;\n"
            "        S_RUN_LAYER:  if (layer_done_sig) state_next = S_NEXT_LAYER;\n"
            "        S_NEXT_LAYER: begin\n"
            "            if (layer_idx == NUM_LAYERS - 1)\n"
            "                state_next = S_SEND_OUT;\n"
            "            else\n"
            "                state_next = S_RUN_LAYER;\n"
            "        end\n"
            "        S_SEND_OUT:   if (axis_out_done) state_next = S_DONE;\n"
            "        S_DONE:       state_next = S_IDLE;\n"
            "        default:      state_next = S_IDLE;\n"
            "    endcase\n"
            "end\n"
            "\n"
            "// State register\n"
            "always_ff @(posedge clk) begin\n"
            "    if (!rst_n || ctrl_soft_rst)\n"
            "        state <= S_IDLE;\n"
            "    else\n"
            "        state <= state_next;\n"
            "end\n"
            "\n"
            "// Layer index\n"
            "always_ff @(posedge clk) begin\n"
            "    if (!rst_n || state == S_IDLE)\n"
            "        layer_idx <= 16'b0;\n"
            "    else if (state == S_NEXT_LAYER)\n"
            "        layer_idx <= layer_idx + 1;\n"
            "end\n"
            "\n"
            "// Control signal generation\n"
            "assign axis_in_enable  = (state == S_RECV_IN);\n"
            "assign axis_out_enable = (state == S_SEND_OUT);\n"
            "assign layer_start     = (state == S_NEXT_LAYER) || "
            "(state == S_RECV_IN && axis_in_done);\n"
            "\n"
            "// Status\n"
            "assign status_idle = (state == S_IDLE);\n"
            "assign status_busy = (state != S_IDLE && state != S_DONE);\n"
            "assign status_error = 1'b0;\n"
            "assign error_code_reg = 32'b0;\n"
            "\n"
            "// Done and interrupt\n"
            "always_ff @(posedge clk) begin\n"
            "    if (!rst_n || state == S_IDLE) begin\n"
            "        status_done_reg <= 1'b0;\n"
            "        irq_done_pulse  <= 1'b0;\n"
            "    end else if (state == S_DONE) begin\n"
            "        status_done_reg <= 1'b1;\n"
            "        irq_done_pulse  <= 1'b1;\n"
            "    end else begin\n"
            "        irq_done_pulse <= 1'b0;\n"
            "    end\n"
            "end\n"
            "\n"
            "assign irq_error_pulse = 1'b0;\n"
            "\n"
            "// Cycle counter\n"
            "always_ff @(posedge clk) begin\n"
            "    if (!rst_n || state == S_IDLE) begin\n"
            "        cycle_counter <= 32'b0;\n"
            "        counting <= 1'b0;\n"
            "    end else if (state == S_RECV_IN && !counting) begin\n"
            "        counting <= 1'b1;\n"
            "        cycle_counter <= 32'b0;\n"
            "    end else if (counting && state != S_DONE) begin\n"
            "        cycle_counter <= cycle_counter + 1;\n"
            "    end\n"
            "end\n"
            "\n"
            "assign cycle_count_reg = cycle_counter;\n"
            "\n"
            "// Inference counter\n"
            "always_ff @(posedge clk) begin\n"
            "    if (!rst_n)\n"
            "        inf_count_reg <= 32'b0;\n"
            "    else if (state == S_DONE && state_next == S_IDLE)\n"
            "        inf_count_reg <= inf_count_reg + 1;\n"
            "end"
        ),
        defines=(
            "state",
            "state_next",
            "layer_idx",
            "axis_in_enable",
            "axis_out_enable",
            "layer_start",
            "status_idle",
            "status_busy",
            "status_error",
            "error_code_reg",
            "status_done_reg",
            "irq_done_pulse",
            "irq_error_pulse",
            "cycle_counter",
            "counting",
            "cycle_count_reg",
            "inf_count_reg",
        ),
        uses=(
            "ctrl_start",
            "ctrl_soft_rst",
            "axis_in_done",
            "axis_out_done",
            "layer_done_sig",
            "rst_n",
            "clk",
        ),
        label="Top-level FSM, status, counters",
    )


# ---------------------------------------------------------------------------
# Tile fabric path (delegated to the legacy generator until lowered)
# ---------------------------------------------------------------------------


def lower_tile_fabric_top(
    graph: Graph,
    fabric: "FabricConfig",
    constraints: HardwareConstraints,
) -> ModuleLibrary:
    """Lower a tile-fabric graph to a ``ModuleLibrary``.

    Stub for now — the tile-fabric lowering is implemented separately in
    ``mlasic.rtl_lowering_tile``. This function will dispatch there once the
    tile-fabric IR conversion lands.
    """
    raise NotImplementedError(
        "Tile fabric lowering is provided by rtl_lowering_tile.lower_tile_fabric"
    )
