// accelerator_top.sv — Auto-generated by MLASIC RTL Generator
// Model: ad_model
// Layers: 4

`include "parameters.svh"

module accelerator_top (
    input clk,
    input rst_n,
    input [7:0] s_axi_awaddr,
    input s_axi_awvalid,
    output logic s_axi_awready,
    input [31:0] s_axi_wdata,
    input [3:0] s_axi_wstrb,
    input s_axi_wvalid,
    output logic s_axi_wready,
    output logic [1:0] s_axi_bresp,
    output logic s_axi_bvalid,
    input s_axi_bready,
    input [7:0] s_axi_araddr,
    input s_axi_arvalid,
    output logic s_axi_arready,
    output logic [31:0] s_axi_rdata,
    output logic [1:0] s_axi_rresp,
    output logic s_axi_rvalid,
    input s_axi_rready,
    input [AXI_DATA_W-1:0] s_axis_tdata,
    input s_axis_tvalid,
    output logic s_axis_tready,
    input s_axis_tlast,
    input [7:0] s_axis_tkeep,
    output logic [AXI_DATA_W-1:0] m_axis_tdata,
    output logic m_axis_tvalid,
    input m_axis_tready,
    output logic m_axis_tlast,
    output logic [7:0] m_axis_tkeep,
    output logic irq
);

    logic ctrl_start;
    logic ctrl_soft_rst;
    logic ctrl_continuous;
    logic irq_en_out;
    logic status_idle;
    logic status_busy;
    logic status_done_reg;
    logic status_error;
    logic [31:0] cycle_count_reg;
    logic [31:0] inf_count_reg;
    logic [31:0] error_code_reg;
    logic irq_done_pulse;
    logic irq_error_pulse;
    logic [15:0] weight_addr;
    logic [128*8-1:0] weight_rdata;
    logic [15:0] bias_addr;
    logic [128*32-1:0] bias_rdata;
    logic input_bank_sel;
    logic [$clog2(ACT_DEPTH)-1:0] act_rd_addr;
    logic [$clog2(ACT_DEPTH)-1:0] act_wr_addr;
    logic [AXI_DATA_W-1:0] act_rd_data;
    logic [AXI_DATA_W-1:0] act_wr_data;
    logic act_wr_en;
    logic [$clog2(ACT_DEPTH)-1:0] axis_in_addr;
    logic [$clog2(ACT_DEPTH)-1:0] axis_out_addr;
    logic axis_in_we;
    logic [AXI_DATA_W-1:0] axis_in_wdata;
    logic [AXI_DATA_W-1:0] axis_out_rdata;
    logic axis_in_enable;
    logic axis_in_done;
    logic axis_out_enable;
    logic axis_out_done;
    logic mac_start;
    logic [15:0] mac_input_dim;
    logic mac_has_relu;
    logic signed [7:0] mac_input_data;
    logic mac_input_valid;
    logic mac_bias_valid;
    logic [6:0] mac_bias_idx;
    logic signed [31:0] mac_bias_data;
    logic [31:0] mac_scale;
    logic [5:0] mac_shift;
    logic signed [7:0] mac_zp;
    logic signed [7:0] mac_output_data [0:128-1];
    logic mac_output_valid;
    logic mac_done_sig;
    logic layer_start;
    logic layer_done_sig;
    logic [31:0] cycle_counter;
    logic counting;
    logic [$clog2(ACT_DEPTH)-1:0] act_a_addr;
    logic [$clog2(ACT_DEPTH)-1:0] act_b_addr;
    logic act_a_we;
    logic act_b_we;
    logic [AXI_DATA_W-1:0] act_a_wdata;
    logic [AXI_DATA_W-1:0] act_b_wdata;
    logic [AXI_DATA_W-1:0] act_a_rdata;
    logic [AXI_DATA_W-1:0] act_b_rdata;

    // ── Top-level FSM state ──
    typedef enum logic [2:0] {
        S_IDLE,
        S_RECV_IN,
        S_RUN_LAYER,
        S_NEXT_LAYER,
        S_SEND_OUT,
        S_DONE
    } accel_state_t;

    accel_state_t state, state_next;
    logic [15:0] layer_idx;

    // ── Verilator lint suppressions ──
    /* verilator lint_off UNUSEDSIGNAL */
    /* verilator lint_off WIDTHTRUNC */
    /* verilator lint_off WIDTHEXPAND */
    /* verilator lint_off PINMISSING */

    // Unified weight bank
    sram_bank #(
        .DEPTH(WEIGHT_DEPTH),
        .WIDTH(128*8),
        .INIT_FILE("weight_bank.mem")
    ) weight_bank (
        .clk(clk),
        .addr(weight_addr[$clog2(WEIGHT_DEPTH)-1:0]),
        .we(1'b0),
        .wdata({128*8{1'b0}}),
        .rdata(weight_rdata)
    );

    // Bias bank
    sram_bank #(
        .DEPTH(BIAS_DEPTH),
        .WIDTH(128*32),
        .INIT_FILE("bias_bank.mem")
    ) bias_bank (
        .clk(clk),
        .addr(bias_addr[$clog2(BIAS_DEPTH)-1:0]),
        .we(1'b0),
        .wdata({128*32{1'b0}}),
        .rdata(bias_rdata)
    );

    sram_bank #(
        .DEPTH(ACT_DEPTH),
        .WIDTH(AXI_DATA_W)
    ) act_a (
        .clk(clk),
        .addr(act_a_addr),
        .we(act_a_we),
        .wdata(act_a_wdata),
        .rdata(act_a_rdata)
    );

    sram_bank #(
        .DEPTH(ACT_DEPTH),
        .WIDTH(AXI_DATA_W)
    ) act_b (
        .clk(clk),
        .addr(act_b_addr),
        .we(act_b_we),
        .wdata(act_b_wdata),
        .rdata(act_b_rdata)
    );

    assign input_bank_sel = layer_idx[0];  // bank select from layer index

    // ── Activation bank mux ──
    always_comb begin
        if (state == S_RECV_IN) begin
            // AXI-Stream input writes to bank A
            act_a_addr = axis_in_addr;
            act_a_we = axis_in_we;
            act_a_wdata = axis_in_wdata;
            act_b_addr = {$clog2(ACT_DEPTH){1'b0}};
            act_b_we = 1'b0;
            act_b_wdata = {AXI_DATA_W{1'b0}};
        end else if (state == S_SEND_OUT) begin
            // AXI-Stream output reads from bank A (last layer)
            act_a_addr = axis_out_addr;
            act_a_we = 1'b0;
            act_a_wdata = {AXI_DATA_W{1'b0}};
            act_b_addr = {$clog2(ACT_DEPTH){1'b0}};
            act_b_we = 1'b0;
            act_b_wdata = {AXI_DATA_W{1'b0}};
        end else if (!input_bank_sel) begin
            // Read from A, write to B
            act_a_addr = act_rd_addr;
            act_a_we = 1'b0;
            act_a_wdata = {AXI_DATA_W{1'b0}};
            act_b_addr = act_wr_addr;
            act_b_we = act_wr_en;
            act_b_wdata = act_wr_data;
        end else begin
            // Read from B, write to A
            act_b_addr = act_rd_addr;
            act_b_we = 1'b0;
            act_b_wdata = {AXI_DATA_W{1'b0}};
            act_a_addr = act_wr_addr;
            act_a_we = act_wr_en;
            act_a_wdata = act_wr_data;
        end
    end

    assign act_rd_data = input_bank_sel ? act_b_rdata : act_a_rdata;

    assign axis_out_rdata = act_a_rdata;

    // AXI-Lite control / status registers
    axi_lite_ctrl #(
        .VERSION(32'h0001_0000)
    ) u_ctrl (
        .clk(clk),
        .rst_n(rst_n),
        .s_axi_awaddr(s_axi_awaddr),
        .s_axi_awvalid(s_axi_awvalid),
        .s_axi_awready(s_axi_awready),
        .s_axi_wdata(s_axi_wdata),
        .s_axi_wstrb(s_axi_wstrb),
        .s_axi_wvalid(s_axi_wvalid),
        .s_axi_wready(s_axi_wready),
        .s_axi_bresp(s_axi_bresp),
        .s_axi_bvalid(s_axi_bvalid),
        .s_axi_bready(s_axi_bready),
        .s_axi_araddr(s_axi_araddr),
        .s_axi_arvalid(s_axi_arvalid),
        .s_axi_arready(s_axi_arready),
        .s_axi_rdata(s_axi_rdata),
        .s_axi_rresp(s_axi_rresp),
        .s_axi_rvalid(s_axi_rvalid),
        .s_axi_rready(s_axi_rready),
        .ctrl_start(ctrl_start),
        .ctrl_soft_rst(ctrl_soft_rst),
        .ctrl_continuous(ctrl_continuous),
        .irq_en(irq_en_out),
        .status_idle(status_idle),
        .status_busy(status_busy),
        .status_done(status_done_reg),
        .status_error(status_error),
        .cycle_count(cycle_count_reg),
        .inf_count(inf_count_reg),
        .error_code(error_code_reg),
        .layer_status(layer_idx[1:0]),
        .irq_done(irq_done_pulse),
        .irq_error(irq_error_pulse),
        .irq(irq)
    );

    axi_stream_in #(
        .AXI_DATA_W(AXI_DATA_W),
        .NUM_BEATS(ACT_DEPTH),
        .ACT_DEPTH(ACT_DEPTH)
    ) u_axis_in (
        .clk(clk),
        .rst_n(rst_n),
        .enable(axis_in_enable),
        .done(axis_in_done),
        .s_axis_tdata(s_axis_tdata),
        .s_axis_tvalid(s_axis_tvalid),
        .s_axis_tready(s_axis_tready),
        .s_axis_tlast(s_axis_tlast),
        .s_axis_tkeep(s_axis_tkeep),
        .act_addr(axis_in_addr),
        .act_we(axis_in_we),
        .act_wdata(axis_in_wdata)
    );

    axi_stream_out #(
        .AXI_DATA_W(AXI_DATA_W),
        .NUM_BEATS(ACT_DEPTH),
        .ACT_DEPTH(ACT_DEPTH)
    ) u_axis_out (
        .clk(clk),
        .rst_n(rst_n),
        .enable(axis_out_enable),
        .done(axis_out_done),
        .m_axis_tdata(m_axis_tdata),
        .m_axis_tvalid(m_axis_tvalid),
        .m_axis_tready(m_axis_tready),
        .m_axis_tlast(m_axis_tlast),
        .m_axis_tkeep(m_axis_tkeep),
        .act_addr(axis_out_addr),
        .act_rdata(axis_out_rdata)
    );

    // Shared MAC array (time-multiplexed across layers)
    mac_array #(
        .PARALLELISM(PARALLELISM),
        .DATA_W(8),
        .ACC_W(32)
    ) u_mac (
        .clk(clk),
        .rst_n(rst_n),
        .start(mac_start),
        .input_dim(mac_input_dim),
        .has_relu(mac_has_relu),
        .weight_data(weight_rdata),
        .weight_valid(1'b1),
        .input_data(mac_input_data),
        .input_valid(mac_input_valid),
        .bias_data(mac_bias_data),
        .bias_valid(mac_bias_valid),
        .bias_idx(mac_bias_idx),
        .scale(mac_scale),
        .shift(mac_shift),
        .zero_point(mac_zp),
        .output_data(mac_output_data),
        .output_valid(mac_output_valid),
        .done(mac_done_sig)
    );

    // Per-layer streaming controller
    fused_linear_relu #(
        .PARALLELISM(PARALLELISM),
        .DATA_W(8),
        .ACC_W(32),
        .ACT_DEPTH(ACT_DEPTH),
        .ACT_WIDTH(AXI_DATA_W)
    ) u_layer_ctrl (
        .clk(clk),
        .rst_n(rst_n),
        .start(layer_start),
        .input_dim(LAYER_IN_DIM[layer_idx]),
        .output_dim(LAYER_OUT_DIM[layer_idx]),
        .num_tiles(LAYER_NUM_TILES[layer_idx]),
        .has_relu(LAYER_RELU[layer_idx]),
        .weight_base(WEIGHT_BASE[layer_idx]),
        .bias_base(BIAS_BASE[layer_idx]),
        .requant_scale(REQUANT_M[layer_idx]),
        .requant_shift(REQUANT_SHIFT[layer_idx]),
        .requant_zp(REQUANT_ZP[layer_idx]),
        .weight_addr(weight_addr),
        .weight_rdata(weight_rdata),
        .bias_addr(bias_addr),
        .bias_rdata(bias_rdata),
        .act_rd_addr(act_rd_addr),
        .act_rd_data(act_rd_data),
        .act_wr_addr(act_wr_addr),
        .act_wr_en(act_wr_en),
        .act_wr_data(act_wr_data),
        .mac_start(mac_start),
        .mac_input_dim(mac_input_dim),
        .mac_has_relu(mac_has_relu),
        .mac_scale(mac_scale),
        .mac_shift(mac_shift),
        .mac_zp(mac_zp),
        .mac_input_data(mac_input_data),
        .mac_input_valid(mac_input_valid),
        .mac_bias_valid(mac_bias_valid),
        .mac_bias_idx(mac_bias_idx),
        .mac_bias_data(mac_bias_data),
        .mac_output_data(mac_output_data),
        .mac_output_valid(mac_output_valid),
        .mac_done(mac_done_sig),
        .layer_done(layer_done_sig)
    );

    // ── Top-level FSM, status, counters ──
    // FSM next-state
    always_comb begin
        state_next = state;
        case (state)
            S_IDLE:       if (ctrl_start) state_next = S_RECV_IN;
            S_RECV_IN:    if (axis_in_done) state_next = S_RUN_LAYER;
            S_RUN_LAYER:  if (layer_done_sig) state_next = S_NEXT_LAYER;
            S_NEXT_LAYER: begin
                if (layer_idx == NUM_LAYERS - 1)
                    state_next = S_SEND_OUT;
                else
                    state_next = S_RUN_LAYER;
            end
            S_SEND_OUT:   if (axis_out_done) state_next = S_DONE;
            S_DONE:       state_next = S_IDLE;
            default:      state_next = S_IDLE;
        endcase
    end

    // State register
    always_ff @(posedge clk) begin
        if (!rst_n || ctrl_soft_rst)
            state <= S_IDLE;
        else
            state <= state_next;
    end

    // Layer index
    always_ff @(posedge clk) begin
        if (!rst_n || state == S_IDLE)
            layer_idx <= 16'b0;
        else if (state == S_NEXT_LAYER)
            layer_idx <= layer_idx + 1;
    end

    // Control signal generation
    assign axis_in_enable  = (state == S_RECV_IN);
    assign axis_out_enable = (state == S_SEND_OUT);
    assign layer_start     = (state == S_NEXT_LAYER) || (state == S_RECV_IN && axis_in_done);

    // Status
    assign status_idle = (state == S_IDLE);
    assign status_busy = (state != S_IDLE && state != S_DONE);
    assign status_error = 1'b0;
    assign error_code_reg = 32'b0;

    // Done and interrupt
    always_ff @(posedge clk) begin
        if (!rst_n || state == S_IDLE) begin
            status_done_reg <= 1'b0;
            irq_done_pulse  <= 1'b0;
        end else if (state == S_DONE) begin
            status_done_reg <= 1'b1;
            irq_done_pulse  <= 1'b1;
        end else begin
            irq_done_pulse <= 1'b0;
        end
    end

    assign irq_error_pulse = 1'b0;

    // Cycle counter
    always_ff @(posedge clk) begin
        if (!rst_n || state == S_IDLE) begin
            cycle_counter <= 32'b0;
            counting <= 1'b0;
        end else if (state == S_RECV_IN && !counting) begin
            counting <= 1'b1;
            cycle_counter <= 32'b0;
        end else if (counting && state != S_DONE) begin
            cycle_counter <= cycle_counter + 1;
        end
    end

    assign cycle_count_reg = cycle_counter;

    // Inference counter
    always_ff @(posedge clk) begin
        if (!rst_n)
            inf_count_reg <= 32'b0;
        else if (state == S_DONE && state_next == S_IDLE)
            inf_count_reg <= inf_count_reg + 1;
    end

endmodule
