// parameters.svh — Auto-generated by MLASIC RTL Generator
// Model: ad_model
// Layers: 4

/* verilator lint_off UNUSEDPARAM */

localparam int NUM_LAYERS   = 4;
localparam int MAX_DIM      = 640;
localparam int PARALLELISM  = 128;
localparam int AXI_DATA_W   = 64;
localparam int WEIGHT_DEPTH = 1536;
localparam int BIAS_DEPTH   = 32;
localparam int ACT_DEPTH    = 80;
localparam int TOTAL_WEIGHT_ROWS = 1536;
localparam int TOTAL_BIAS_ROWS   = 32;

// Per-layer dimensions
localparam logic [15:0] LAYER_IN_DIM  [0:3] = '{16'd640, 16'd128, 16'd128, 16'd128};
localparam logic [15:0] LAYER_OUT_DIM [0:3] = '{16'd128, 16'd128, 16'd128, 16'd640};
localparam logic [15:0] LAYER_NUM_TILES [0:3] = '{16'd1, 16'd1, 16'd1, 16'd5};
localparam logic [0:0]  LAYER_RELU   [0:3] = '{1'b1, 1'b1, 1'b1, 1'b0};

// Weight/bias SRAM base addresses
localparam logic [15:0] WEIGHT_BASE [0:3] = '{16'd0, 16'd640, 16'd768, 16'd896};
localparam logic [15:0] BIAS_BASE   [0:3] = '{16'd0, 16'd4, 16'd8, 16'd12};

// Requantization parameters
localparam logic [31:0] REQUANT_M     [0:3] = '{32'd170, 32'd261, 32'd287, 32'd120};
localparam logic [5:0]  REQUANT_SHIFT [0:3] = '{6'd16, 6'd16, 6'd16, 6'd16};
localparam logic signed [7:0]  REQUANT_ZP    [0:3] = '{-8'sd128, -8'sd128, -8'sd128, -8'sd15};
