# ==============================================================================
# constraints.xdc -- Timing and Physical Constraints for Kria KV260
# ==============================================================================
#
# Purpose:
#   Extended timing constraints for the MLASIC accelerator on Zynq UltraScale+.
#   Builds upon the base constraints in rtl/constraints/constraints.xdc with
#   UltraScale+-specific settings for the Kria KV260 SOM.
#
# Target: Xilinx Kria KV260 (xck26-sfvc784-2LV)
# Clock: 100 MHz PL clock from PS FCLK_CLK0 (pl_clk0)
#
# Usage:
#   Added automatically by build.tcl during synthesis. Can also be added
#   manually via: add_files -fileset constrs_1 fpga/constraints.xdc
# ==============================================================================

# ------------------------------------------------------------------------------
# Section 1: Clock Definition
# ------------------------------------------------------------------------------
# The PL clock is generated by the PS block (FCLK_CLK0 / pl_clk0).
# In block design flows, Vivado auto-generates the clock constraint from the
# PS configuration. This explicit constraint serves as documentation and as
# a fallback for non-block-design synthesis runs.
#
# 100 MHz = 10.000 ns period
create_clock -period 10.000 -name pl_clk0 [get_pins -hierarchical -filter {NAME =~ */pl_clk0}]

# ------------------------------------------------------------------------------
# Section 2: Asynchronous Reset False Paths
# ------------------------------------------------------------------------------
# The reset signal (rst_n) is synchronized by proc_sys_reset in the block
# design. The raw reset from PS is asynchronous to PL clock and must be
# excluded from timing analysis. The synchronized version (peripheral_aresetn)
# is fully synchronous and does not need a false path.
set_false_path -from [get_cells -hierarchical -filter {NAME =~ *proc_sys_reset*/U0/ACTIVE_LOW_PR_OUT_DFF[0].FDRE_PER_N}]

# ------------------------------------------------------------------------------
# Section 3: AXI Interface I/O Delay Constraints
# ------------------------------------------------------------------------------
# These constraints apply to the internal AXI interfaces between PS and PL.
# On Zynq UltraScale+, PS-PL AXI interfaces are internal (no I/O pads), so
# Vivado handles their timing automatically via the PS IP timing model.
# The constraints below are documentation/safety nets for the internal paths.

# AXI-Lite (HPM0_LPD -> Accelerator CSR, 32-bit, 100 MHz)
# Max combinational delay budget: 3 ns setup, 1 ns hold
set_max_delay -datapath_only 8.0 \
    -from [get_cells -hierarchical -filter {NAME =~ *axi_interconnect*/*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *accelerator_top*/*axi_lite*}]

# AXI-Stream (DMA MM2S -> Accelerator input, 64-bit)
# Ensure stream data meets setup at destination
set_max_delay -datapath_only 8.0 \
    -from [get_cells -hierarchical -filter {NAME =~ *axi_dma*/*mm2s*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *accelerator_top*/*stream_in*}]

# AXI-Stream (Accelerator output -> DMA S2MM, 64-bit)
set_max_delay -datapath_only 8.0 \
    -from [get_cells -hierarchical -filter {NAME =~ *accelerator_top*/*stream_out*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *axi_dma*/*s2mm*}]

# ------------------------------------------------------------------------------
# Section 4: Interrupt Signal Constraints
# ------------------------------------------------------------------------------
# The interrupt (irq) from accelerator to PS IRQ_F2P must arrive within
# one clock period. This is an internal signal, not a pad, but we constrain
# it to ensure timing closure on the interrupt path.
set_max_delay -datapath_only 10.0 \
    -from [get_cells -hierarchical -filter {NAME =~ *accelerator_top*/*irq*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *zynq_ultra_ps*/*IRQ*}]

# ------------------------------------------------------------------------------
# Section 5: Clock Domain Crossing (CDC) Constraints
# ------------------------------------------------------------------------------
# In v0.1, the entire PL design runs on a single clock domain (pl_clk0).
# No CDC constraints are needed. This section is reserved for future use
# when multiple clock domains may be introduced (e.g., memory clock).

# ------------------------------------------------------------------------------
# Section 6: BRAM Inference Guidance
# ------------------------------------------------------------------------------
# Ensure Vivado infers BRAM for weight and activation SRAMs rather than
# distributed RAM. These are set as synthesis attributes in the RTL
# (ram_style = "block"), but we reinforce them here.
# Note: These are applied via set_property on the synthesis run, not in XDC.
# Included here as documentation.
#
# set_property STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS {-ram_style block} [get_runs synth_1]

# ------------------------------------------------------------------------------
# Section 7: Bitstream Configuration for Kria KV260
# ------------------------------------------------------------------------------
# Kria SOM boots from QSPI and loads PL via PCAP. These properties ensure
# the bitstream is compatible with the KV260 boot flow.

# General configuration settings
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

# Configuration voltage for the SOM
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]

# Security: disable readback for production (can enable for debug)
set_property BITSTREAM.READBACK.ACTIVERECONFIG NO [current_design]

# DCI cascade (Kria SOM specific -- avoid DCI conflicts with SOM design)
# The KV260 SOM handles DCI internally; PL user design should not drive DCI.

# ------------------------------------------------------------------------------
# Section 8: Timing Exceptions for Debug (Optional)
# ------------------------------------------------------------------------------
# Uncomment the following to relax timing on ILA debug cores if added.
# set_false_path -to [get_cells -hierarchical -filter {NAME =~ *ila_*}]
# set_false_path -to [get_cells -hierarchical -filter {NAME =~ *dbg_hub*}]

# ==============================================================================
# End of constraints
# ==============================================================================
