/*
 * test_vectors.h -- Compile-time test data for accelerator self-test
 *
 * Auto-generated by: mlasic compile --emit-test-vectors
 * Replace with actual golden vectors from the quantized model.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef TEST_VECTORS_H
#define TEST_VECTORS_H

#include <stdint.h>
#include "accel_regs.h"

#define NUM_TEST_VECTORS  1

/* Test input: 640 INT8 values (placeholder -- all zeros).
 * Replace with calibration data from the AD model dataset.                  */
static const int8_t test_input[INPUT_SIZE_BYTES] = { 0 };

/* Golden output: 640 INT8 values (placeholder -- all zeros).
 * Replace with output from the quantized IR interpreter run on test_input.  */
static const int8_t expected_output[OUTPUT_SIZE_BYTES] = { 0 };

#endif /* TEST_VECTORS_H */
